### ISSUE TITLE
Question: increase max file uploads

### ISSUE THREAD

**Issue by JoostFaber** [afterlogic/aurora-files#24]
Hi,

Currently we are testing AuroraFiles to see if it's suitable for us.
In one of our testcases we have tried to upload a complete directory structure with a lot of documents.
For example:

- Main folder
  - Sub folder 1
    -Sub_Sub_folder 1
  - Sub folder 2
    -Sub_Sub_folder 1 
    -Sub_Sub_folder 2 
  - Sub folder 3

Each folder will have aprox 25 files.

What we have found is that the application only uploads 50 files at a time and doesn't reconstructs the directory structure.
We have tried to upload the complete directory structure with all files at once, so from the main folder.

My Questions are:
1. Is this functionality currently supported?
2. How to increase the max file uploads?

I have increased the max_post_size, upload_max_filesize and max_file_uploads in PHP.ini but this doesn't solve the problem.

**Amount of files near trashcan is 50. based on a single upload**
![max_50_uploads](https://user-images.githubusercontent.com/11028935/89652858-66eaa780-d8c6-11ea-8c19-4b1915ef97ab.png)

**Comment by afterlogic-support** [comment]
File storage doesn't currently support uploading directories with subdirectory structure maintained, it only uploads files. We may be able to add support for directory uploads in the future releases.

As for the multiple file upload limit, there's one in the code indeed. You need to locate the following line in `modules/CoreWebclient/js/CJua.js` file:

```js
'multipleSizeLimit': 50,
```

and set it to a higher value. To apply changes, you'll need to rebuild static files [as shown here](https://afterlogic.com/docs/aurora-files/installation/adding-modules).

If rebuilding JS isn't feasible for any reason, there's another option. Under `static/js` directory, locate files `FilesWebclient.app.some-hash-here.js` and `MailWebclient.app.some-hash-here.js ` (those without `.min.js` in the name) and perform the above change there. Then set **UseAppMinJs** to **false** in `data/settings/config.json` file so that non-minified JS is used.

**Comment by JoostFaber** [comment]
Hi  Afterlogic-support,

The multipleSizeLimit part is tackled and we are able to upload more than 50 files at once.
Shall i close this ticket or edit the question to upload directories with subdirectories?

**Comment by afterlogic-support** [comment]
Developers are working on correcting the issue right now, so the expected behavior should be there in the next version.
Also, the next version will have a configuration option so it won't be necessary to adjust multipleSizeLimit directly in the code.
My suggestion is to keep this thread open till both the issues are addressed in a public release. Thank you.

**Comment by afterlogic-support** [comment]
We've just released version 8.5.1, uploading directory with subdirectories should work correctly there, and **MultipleFilesUploadLimit** setting is added to `data/settings/modules/CoreWebclient.config.json` configuration file.
