### ISSUE TITLE
Can be integrated Aurora Files with WebMail Lite ?

### ISSUE THREAD

**Issue by piratov** [afterlogic/aurora-files#59]
There are installed versions
Afterlogic Aurora Files Version 9.7.4.build3-build-o3
Afterlogic WebMail Lite PHP Version 9.7.4.build3-build-o3

Another question about sharing a folder?
![image](https://github.com/afterlogic/aurora-files/assets/17856390/1ce86867-84b6-440a-8435-a0a9499726a9)

**Comment by afterlogic-support** [comment]
The two products cannot be integrated directly, particularly since they use quite different models of authentication. In Aurora Files, you authenticate against a database, while in WebMail the authentication is done on IMAP level.

I'd recommend taking a look at WebMail Pro which offers both email and files functionality:

https://afterlogic.com/webmail-client

Not too sure I understand the second question though. As the message indicates, you can create a link for a folder, but cannot password-protect it.

**Comment by piratov** [comment]
> The two products cannot be integrated directly, particularly since they use quite different models of authentication. In Aurora Files, you authenticate against a database, while in WebMail the authentication is done on IMAP level.
> 
> I'd recommend taking a look at WebMail Pro which offers both email and files functionality:
> 
> https://afterlogic.com/webmail-client
Thanks, I will take a look

> 
> Not too sure I understand the second question though. As the message indicates, you can create a link for a folder, but cannot password-protect it.
>
Yes, folder cannot password-protect it?

**Comment by afterlogic-support** [comment]
That is correct.

**Comment by piratov** [comment]
> That is correct.

Is this somewhere in the setting where you can select whether to enable or disable creating folder access using a password-protect?

**Comment by afterlogic-support** [comment]
No, that simply isn't supported.

Note that Aurora Files is a free opensource product, you can modify its source and add any features you require.
